# Generated by Django 5.0.14 on 2026-01-10 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("utilities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tariff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the tariff (e.g., PG&E B-19)", max_length=200
                    ),
                ),
                (
                    "utility",
                    models.ForeignKey(
                        help_text="Utility company offering this tariff",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tariffs",
                        to="utilities.utility",
                    ),
                ),
            ],
            options={
                "ordering": ["utility__name", "name"],
                "unique_together": {("utility", "name")},
            },
        ),
        migrations.CreateModel(
            name="EnergyCharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the charge (e.g., Summer Peak Energy)",
                        max_length=200,
                    ),
                ),
                (
                    "rate_usd_per_kwh",
                    models.DecimalField(
                        decimal_places=5, help_text="Rate in $/kWh", max_digits=10
                    ),
                ),
                (
                    "period_start_time_utc",
                    models.TimeField(
                        help_text="Start time of the period in UTC (inclusive)"
                    ),
                ),
                (
                    "period_end_time_utc",
                    models.TimeField(
                        help_text="End time of the period in UTC (exclusive of the next minute)"
                    ),
                ),
                (
                    "applies_start_date",
                    models.DateField(
                        blank=True,
                        help_text="First date of the year that this charge applies (inclusive). Null if year-round.",
                        null=True,
                    ),
                ),
                (
                    "applies_end_date",
                    models.DateField(
                        blank=True,
                        help_text="Last date of the year that this charge applies (inclusive). Null if year-round.",
                        null=True,
                    ),
                ),
                (
                    "applies_weekends",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this charge applies on weekends",
                    ),
                ),
                (
                    "applies_holidays",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this charge applies on utility holidays",
                    ),
                ),
                (
                    "applies_weekdays",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this charge applies on weekdays",
                    ),
                ),
                (
                    "tariff",
                    models.ForeignKey(
                        help_text="Tariff this charge belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="energy_charges",
                        to="tariffs.tariff",
                    ),
                ),
            ],
            options={
                "ordering": ["tariff", "name"],
            },
        ),
        migrations.CreateModel(
            name="DemandCharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the charge (e.g., Summer Peak Demand)",
                        max_length=200,
                    ),
                ),
                (
                    "rate_usd_per_kw",
                    models.DecimalField(
                        decimal_places=2, help_text="Rate in $/kW", max_digits=10
                    ),
                ),
                (
                    "period_start_time_utc",
                    models.TimeField(
                        help_text="Start time of the period in UTC (inclusive)"
                    ),
                ),
                (
                    "period_end_time_utc",
                    models.TimeField(
                        help_text="End time of the period in UTC (exclusive of the next minute)"
                    ),
                ),
                (
                    "applies_start_date",
                    models.DateField(
                        blank=True,
                        help_text="First date this charge applies (inclusive). Null if year-round.",
                        null=True,
                    ),
                ),
                (
                    "applies_end_date",
                    models.DateField(
                        blank=True,
                        help_text="Last date this charge applies (inclusive). Null if year-round.",
                        null=True,
                    ),
                ),
                (
                    "applies_weekends",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this charge applies on weekends",
                    ),
                ),
                (
                    "applies_holidays",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this charge applies on utility holidays",
                    ),
                ),
                (
                    "applies_weekdays",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this charge applies on weekdays",
                    ),
                ),
                (
                    "peak_type",
                    models.CharField(
                        choices=[("daily", "Daily"), ("monthly", "Monthly")],
                        default="monthly",
                        help_text="Whether peak is calculated daily or monthly",
                        max_length=10,
                    ),
                ),
                (
                    "tariff",
                    models.ForeignKey(
                        help_text="Tariff this charge belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demand_charges",
                        to="tariffs.tariff",
                    ),
                ),
            ],
            options={
                "ordering": ["tariff", "name"],
            },
        ),
        migrations.CreateModel(
            name="CustomerCharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the charge (e.g., Customer Charge)",
                        max_length=200,
                    ),
                ),
                (
                    "usd_per_month",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Fixed charge in $/month",
                        max_digits=10,
                    ),
                ),
                (
                    "tariff",
                    models.ForeignKey(
                        help_text="Tariff this charge belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_charges",
                        to="tariffs.tariff",
                    ),
                ),
            ],
            options={
                "ordering": ["tariff", "name"],
            },
        ),
    ]
