# Generated by Django 5.0.14 on 2026-01-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tariffs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="demandcharge",
            name="period_end_time_local",
            field=models.TimeField(
                help_text="End time of the period in customer's local time (exclusive of the next minute)"
            ),
        ),
        migrations.AlterField(
            model_name="demandcharge",
            name="period_start_time_local",
            field=models.TimeField(
                help_text="Start time of the period in customer's local time (inclusive)"
            ),
        ),
        migrations.AlterField(
            model_name="energycharge",
            name="period_end_time_local",
            field=models.TimeField(
                help_text="End time of the period in customer's local time (exclusive of the next minute)"
            ),
        ),
        migrations.AlterField(
            model_name="energycharge",
            name="period_start_time_local",
            field=models.TimeField(
                help_text="Start time of the period in customer's local time (inclusive)"
            ),
        ),
    ]
