# Generated by Django 5.0.14 on 2026-01-13 01:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tariffs", "0002_alter_demandcharge_period_end_time_local_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customercharge",
            name="usd_per_month",
            field=models.DecimalField(
                decimal_places=5, help_text="Fixed charge in $/month", max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="demandcharge",
            name="rate_usd_per_kw",
            field=models.DecimalField(
                decimal_places=5, help_text="Rate in $/kW", max_digits=10
            ),
        ),
    ]
