# Generated by Django 5.0.14 on 2026-01-13 04:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tariffs", "0003_alter_customercharge_usd_per_month_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customercharge",
            old_name="usd_per_month",
            new_name="amount_usd",
        ),
        migrations.AddField(
            model_name="customercharge",
            name="charge_type",
            field=models.CharField(
                choices=[("daily", "Daily"), ("monthly", "Monthly")],
                default="monthly",
                help_text="Whether this is a daily or monthly charge",
                max_length=10,
            ),
        ),
    ]
