# Generated by Django 5.0.14 on 2026-01-14 02:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tariffs", "0004_add_customer_charge_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customercharge",
            name="amount_usd",
            field=models.DecimalField(
                decimal_places=5,
                help_text="Fixed charge amount in USD (per day or per month depending on charge_type)",
                max_digits=10,
            ),
        ),
    ]
