# Generated by Django 5.0.14 on 2026-01-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tariffs", "0005_alter_customercharge_amount_usd"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicabilityRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Descriptive name (e.g., 'Summer Peak Hours')",
                        max_length=200,
                    ),
                ),
                (
                    "period_start_time_local",
                    models.TimeField(
                        blank=True,
                        help_text="Start time (inclusive). Null = start of day.",
                        null=True,
                    ),
                ),
                (
                    "period_end_time_local",
                    models.TimeField(
                        blank=True,
                        help_text="End time (exclusive). Null = end of day.",
                        null=True,
                    ),
                ),
                (
                    "applies_start_date",
                    models.DateField(
                        blank=True,
                        help_text="Seasonal start (month/day only). Null = year-round.",
                        null=True,
                    ),
                ),
                (
                    "applies_end_date",
                    models.DateField(
                        blank=True,
                        help_text="Seasonal end (month/day only). Null = year-round.",
                        null=True,
                    ),
                ),
                (
                    "applies_weekdays",
                    models.BooleanField(
                        default=True, help_text="Whether this rule applies on weekdays"
                    ),
                ),
                (
                    "applies_weekends",
                    models.BooleanField(
                        default=True, help_text="Whether this rule applies on weekends"
                    ),
                ),
                (
                    "applies_holidays",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this rule applies on utility holidays",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="demandcharge",
            name="applicability_rules",
            field=models.ManyToManyField(
                blank=True,
                help_text="Applicability rules (combined with OR logic)",
                related_name="demand_charges",
                to="tariffs.applicabilityrule",
            ),
        ),
        migrations.AddField(
            model_name="energycharge",
            name="applicability_rules",
            field=models.ManyToManyField(
                blank=True,
                help_text="Applicability rules (combined with OR logic)",
                related_name="energy_charges",
                to="tariffs.applicabilityrule",
            ),
        ),
    ]
