# Generated by Django 5.0.14 on 2026-01-14 14:31

from django.db import migrations


def forwards(apps, schema_editor):
    """
    Convert existing embedded applicability fields to ApplicabilityRule records.

    For each existing charge, create an ApplicabilityRule from its embedded fields
    and link it via the M2M relationship.
    """
    ApplicabilityRule = apps.get_model("tariffs", "ApplicabilityRule")
    EnergyCharge = apps.get_model("tariffs", "EnergyCharge")
    DemandCharge = apps.get_model("tariffs", "DemandCharge")

    # Migrate energy charges
    for charge in EnergyCharge.objects.all():
        rule = ApplicabilityRule.objects.create(
            name=f"{charge.name} Rule",
            period_start_time_local=charge.period_start_time_local,
            period_end_time_local=charge.period_end_time_local,
            applies_start_date=charge.applies_start_date,
            applies_end_date=charge.applies_end_date,
            applies_weekdays=charge.applies_weekdays,
            applies_weekends=charge.applies_weekends,
            applies_holidays=charge.applies_holidays,
        )
        charge.applicability_rules.add(rule)

    # Migrate demand charges
    for charge in DemandCharge.objects.all():
        rule = ApplicabilityRule.objects.create(
            name=f"{charge.name} Rule",
            period_start_time_local=charge.period_start_time_local,
            period_end_time_local=charge.period_end_time_local,
            applies_start_date=charge.applies_start_date,
            applies_end_date=charge.applies_end_date,
            applies_weekdays=charge.applies_weekdays,
            applies_weekends=charge.applies_weekends,
            applies_holidays=charge.applies_holidays,
        )
        charge.applicability_rules.add(rule)


def backwards(apps, schema_editor):
    """
    Reverse the migration by deleting all ApplicabilityRule records.

    The embedded fields on charges are preserved, so no data loss occurs.
    """
    ApplicabilityRule = apps.get_model("tariffs", "ApplicabilityRule")
    ApplicabilityRule.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("tariffs", "0006_add_applicability_rule_model"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
