# Generated by Django 5.0.14 on 2026-01-14 16:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tariffs", "0007_migrate_applicability_rules"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="demandcharge",
            name="applies_end_date",
        ),
        migrations.RemoveField(
            model_name="demandcharge",
            name="applies_holidays",
        ),
        migrations.RemoveField(
            model_name="demandcharge",
            name="applies_start_date",
        ),
        migrations.RemoveField(
            model_name="demandcharge",
            name="applies_weekdays",
        ),
        migrations.RemoveField(
            model_name="demandcharge",
            name="applies_weekends",
        ),
        migrations.RemoveField(
            model_name="demandcharge",
            name="period_end_time_local",
        ),
        migrations.RemoveField(
            model_name="demandcharge",
            name="period_start_time_local",
        ),
        migrations.RemoveField(
            model_name="energycharge",
            name="applies_end_date",
        ),
        migrations.RemoveField(
            model_name="energycharge",
            name="applies_holidays",
        ),
        migrations.RemoveField(
            model_name="energycharge",
            name="applies_start_date",
        ),
        migrations.RemoveField(
            model_name="energycharge",
            name="applies_weekdays",
        ),
        migrations.RemoveField(
            model_name="energycharge",
            name="applies_weekends",
        ),
        migrations.RemoveField(
            model_name="energycharge",
            name="period_end_time_local",
        ),
        migrations.RemoveField(
            model_name="energycharge",
            name="period_start_time_local",
        ),
    ]
