# Generated by Django 5.0.14 on 2026-01-10 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interval_start_utc",
                    models.DateTimeField(
                        db_index=True,
                        help_text="Start of the 5-minute interval in UTC (inclusive)",
                    ),
                ),
                (
                    "energy_kwh",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Energy consumption in kWh for this interval",
                        max_digits=12,
                    ),
                ),
                (
                    "peak_demand_kw",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Peak power demand in kW during this interval",
                        max_digits=12,
                    ),
                ),
                (
                    "temperature_c",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Temperature in Celsius (optional)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "created_at_utc",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="Customer",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_records",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Customer usage records",
                "ordering": ["customer", "interval_start_utc"],
                "indexes": [
                    models.Index(
                        fields=["customer", "interval_start_utc"],
                        name="usage_custo_custome_a6d85f_idx",
                    )
                ],
                "unique_together": {("customer", "interval_start_utc")},
            },
        ),
    ]
