# Generated by Django 5.0.14 on 2026-01-12 20:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerusage",
            name="interval_end_utc",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="End of the billing interval in UTC (exclusive)",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customerusage",
            name="interval_start_utc",
            field=models.DateTimeField(
                db_index=True,
                help_text="Start of the billing interval in UTC (inclusive)",
            ),
        ),
    ]
