# Generated by Django 5.0.14 on 2026-01-13 02:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usage", "0002_customerusage_interval_end_utc_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerusage",
            name="temperature_c",
            field=models.FloatField(
                blank=True, help_text="Temperature in Celsius (optional)", null=True
            ),
        ),
    ]
