# Generated by Django 5.0.14 on 2026-01-10 18:11

import django.db.models.deletion
import timezone_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tariffs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the customer", max_length=200),
                ),
                (
                    "timezone",
                    timezone_field.fields.TimeZoneField(
                        default="America/Los_Angeles",
                        help_text="IANA timezone for this customer's location",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "current_tariff",
                    models.ForeignKey(
                        help_text="Current tariff for this customer",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="current_customers",
                        to="tariffs.tariff",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
