# Generated by Django 5.0.14 on 2026-01-10 17:22

import django.db.models.deletion
import timezone_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tariffs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the customer", max_length=200),
                ),
                (
                    "timezone",
                    timezone_field.fields.TimeZoneField(
                        default="America/Los_Angeles",
                        help_text="IANA timezone for this customer's location",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "current_tariff",
                    models.ForeignKey(
                        blank=True,
                        help_text="Current tariff for this customer",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_customers",
                        to="tariffs.tariff",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CustomerTariffHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "effective_from",
                    models.DateField(
                        help_text="Date this tariff became effective for the customer"
                    ),
                ),
                (
                    "effective_to",
                    models.DateField(
                        blank=True,
                        help_text="Date this tariff stopped being effective (null if current)",
                        null=True,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="Customer",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tariff_history",
                        to="customers.customer",
                    ),
                ),
                (
                    "tariff",
                    models.ForeignKey(
                        help_text="Tariff",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_history",
                        to="tariffs.tariff",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Customer tariff histories",
                "ordering": ["customer", "-effective_from"],
                "unique_together": {("customer", "effective_from")},
            },
        ),
    ]
