# Generated by Django 5.0.14 on 2026-01-11 17:45

import timezone_field.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="timezone",
            field=timezone_field.fields.TimeZoneField(
                help_text="IANA timezone for this customer's location"
            ),
        ),
    ]
