# Generated by Django 5.0.14 on 2026-01-12 20:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0002_remove_timezone_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="billing_interval_minutes",
            field=models.IntegerField(
                default=5,
                help_text="Duration of billing intervals in minutes",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
