# Generated by Django 5.0.14 on 2026-01-14 03:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0003_customer_billing_interval_minutes"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="billing_day",
            field=models.IntegerField(
                default=1,
                help_text="Day of month when billing cycle ends (1-28)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(28),
                ],
            ),
        ),
    ]
