# Generated by Django 5.0.14 on 2026-01-10 21:58

import django.db.models.deletion
import timezone_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Utility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the utility company",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "timezone",
                    timezone_field.fields.TimeZoneField(
                        help_text="IANA timezone for this utility's service area"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Utilities",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the holiday (e.g., Independence Day)",
                        max_length=200,
                    ),
                ),
                ("date", models.DateField(help_text="Date of the holiday")),
                (
                    "utility",
                    models.ForeignKey(
                        help_text="Utility company",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holidays",
                        to="utilities.utility",
                    ),
                ),
            ],
            options={
                "ordering": ["utility", "date"],
                "unique_together": {("utility", "date")},
            },
        ),
    ]
