# Generated by Django 5.0.14 on 2026-01-11 17:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("utilities", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="utility",
            name="timezone",
        ),
    ]
